### ISSUE TITLE
Wrong ports documented for RPC

### ISSUE THREAD

**Issue by greenbigfrog** [iancoin/iancoin#3]
The default port for RPC appears to be 13765, and not 9998 as documented at https://github.com/iancoin/iancoin/blob/a784f24e79d151a4cdbdfa4bc904869b3354be84/src/iancoin-cli.cpp#L37 and https://github.com/iancoin/iancoin/blob/a784f24e79d151a4cdbdfa4bc904869b3354be84/src/init.cpp#L489

**Comment by iancoin** [comment]
fixed
